### ISSUE TITLE
Script doesn't clean up after itself.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu-Lua/Pessi#1]
If you do something like the 15M transaction, then buy something like a property or an upgrade, instead of costing money, you will be given another 15M. This is dangerous as you're repeating the same transaction twice.

**Comment by abuazizv** [comment]
I just noticed this after a week sorry I don't pay attention to github that much, will take a look into the issue.

**Comment by abuazizv** [comment]
however it shouldn't be risky, this 15M transaction is limited not sure how you managed to repeat it twice.

it may take a while for me to reproduce this i only have one account now lol, and i really don't wanna inject YimMenu in the meantime.

**Comment by abuazizv** [comment]
ok so a rewrite is coming soon lol should fix this issue
